### ISSUE TITLE
Error if two nodes are active at can bus

### ISSUE THREAD

**Issue by Joezi79** [nielstron/pyblnet#33]
I have a problem with pyblnet and home assistant. I am getting the following error message:

Traceback (most recent call last):
File “/usr/src/homeassistant/homeassistant/setup.py”, line 213, in async_setup_component
result = await task
File “/usr/local/lib/python3.8/concurrent/futures/thread.py”, line 57, in run
result = self.fn(*self.args, **self.kwargs)
File “/config/custom_components/blnet/init.py”, line 102, in setup
data = fetch_data()
File “/config/custom_components/blnet/init.py”, line 98, in fetch_data
return hass.data["DATA{}".format(DOMAIN)].update()
File “/config/custom_components/blnet/init.py”, line 146, in update
data = self.blnet.fetch(self.node)
File “/usr/local/lib/python3.8/site-packages/pyblnet/blnet.py”, line 91, in fetch
direct = self.blnet_direct.get_latest(self.max_retries)[0]
File “/usr/local/lib/python3.8/site-packages/pyblnet/blnet_conn.py”, line 304, in get_latest
self.get_count()
File “/usr/local/lib/python3.8/site-packages/pyblnet/blnet_conn.py”, line 84, in get_count
checksum) = struct.unpack(’<5sB3s3sB’)
TypeError: unpack expected 2 arguments, got 1

I have two network nodes at can bus. Here is my yaml config
‘’’
blnet:
resource: “http://192.168.178.222”
password: 12345
use_web: true
use_ta: true
web_port: 355
ta_port: 40000
can_node: 32
‘’’
It works if I set use_ta to false. Does anyone have an idea to overcome this situation?

**Comment by nielstron** [comment]
As described in the README, the `use_ta` option is disabled by default for the simple reason that it causes exceptions like the described one. Please disable it to avoid issues.

**Comment by Joezi79** [comment]
Ok. Thank you very much for your fast reply. I enabled it in the hope to get some more values like heating quantity.
