### ISSUE TITLE
Bug in blnet_web.py

### ISSUE THREAD

**Issue by whatashit** [nielstron/pyblnet#37]
After having some issues with a UVR1611 not being node 1 I found out that there is most probably a bug in blnet_web.py

Line 166. In `def set_node(self, node):`

The http request changes the node number of the BLNET not the UVR1611.

 `self.ip + "/can.htm?blaA=" + str(node)`

should be changed to

`self.ip + "/can.htm?blaB=" + str(node)`

**Comment by nielstron** [comment]
Thanks for raising this! I will incorporate this change. I am wondering if anyone else has experienced this issue as well?

**Comment by whatashit** [comment]
@nielstron 
I guess the UVR1611 and BLNET are not so common anymore as new heating systems have usually very good control possibilities and also network integration. But I still love the UVR. 
I came accross that issue because of the need to change to a different node. And I saw connection is only possible after manual selection and the next couple of hours. 
I still have some issues. So maybe I need to dig into this deeper again some day.

**Comment by whatashit** [comment]
@nielstron 

Hello Niels,

looks like you fixed the bug. What are the next steps to get this version. HA picks the version automatically (I guess based on some request in the BLNET integration). 
This bug-fix would also fix the issue we are having loosing the connection to UVR1611. As right now you cannot define a node in the configuration. If no node is provided the module "set_node" will never be executed. This small fix would really help.

There is now a pull request. Can I do anything or provide some help? Sorry I'm new to Github....
